2025/10/18 01:54:32 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: 192.168.1.2, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.5:9000", host: "localhost:8087"
2025/10/18 01:54:34 [error] 30#30: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: 192.168.1.2, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.5:9000", host: "localhost:8087"
2025/10/18 01:55:50 [error] 31#31: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: 192.168.1.2, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.5:9000", host: "localhost:8087"
2025/10/18 01:58:02 [error] 32#32: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: 192.168.1.2, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.5:9000", host: "localhost:8087"
2025/10/18 01:58:59 [error] 32#32: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: 192.168.1.2, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.5:9000", host: "localhost:8087"
2025/10/18 01:59:03 [error] 32#32: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: 192.168.1.2, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.5:9000", host: "localhost:8087"
